workflows:
  android-workflow:
    name: Build Android Debug APK
    max_build_duration: 60
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk

