workflows:
  android-workflow:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
      flutter: false
      android:
        gradle_options: "--no-daemon"
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
